### ISSUE TITLE
Copy/paste on socket group

### ISSUE THREAD

**Issue by tonytamps** [LocalIdentity/PathOfBuilding#18]
When pressing Ctrl+C on a socket group the program throw this error 

![image](https://user-images.githubusercontent.com/2356776/70359346-cd4e9e80-18cf-11ea-8e62-e57888889ac3.png)

Seems to only be this build and on any socket group - 
https://pastebin.com/Uysh0Wcn

**Comment by tonytamps** [comment]
Apparently the word nil in the label is the cause but probably shouldn't be happening anyway

**Comment by ManWithBear** [comment]
Is it happens only with `nil` in label?

**Comment by ppoelzl** [comment]
It's not nil as in a string called "nil" but actually the type nil, aka empty or undefined.
Somehow this build go corrupted, but you can fix it by renaming each label to something else, even "nil".
I don't think a code change is necessary since this should not happen in the first place, but if you wanted to, you could check for truthy-ness on the label like:
if socketGroup.label and socketGroup.label:match("%S") then
on line 264 in /Classes/SkillsTab.lua
